// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvK1hYqN5RLw4njGyhBeMCcGp7Q6Hg2lQ',
    appId: '1:1023919741078:web:85582adeab0fe51b638ab7',
    messagingSenderId: '1023919741078',
    projectId: 'new-project-a7335',
    authDomain: 'new-project-a7335.firebaseapp.com',
    storageBucket: 'new-project-a7335.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJcX6sZUI7diVmCBzt-pStSs0VGcmS_t4',
    appId: '1:1023919741078:android:57ca7b54c3a078fe638ab7',
    messagingSenderId: '1023919741078',
    projectId: 'new-project-a7335',
    storageBucket: 'new-project-a7335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwF8kZqkUVJ6JBiLMJ3d_PhTyITT-xNc',
    appId: '1:1023919741078:ios:3560b94d17d5ef3f638ab7',
    messagingSenderId: '1023919741078',
    projectId: 'new-project-a7335',
    storageBucket: 'new-project-a7335.appspot.com',
    iosClientId: '1023919741078-3tsak8emhpqg33it9ahfsrgclks9qsib.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZwF8kZqkUVJ6JBiLMJ3d_PhTyITT-xNc',
    appId: '1:1023919741078:ios:3560b94d17d5ef3f638ab7',
    messagingSenderId: '1023919741078',
    projectId: 'new-project-a7335',
    storageBucket: 'new-project-a7335.appspot.com',
    iosClientId: '1023919741078-3tsak8emhpqg33it9ahfsrgclks9qsib.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );
}
